-- MySQL Script generated by MySQL Workbench
-- 10/12/14 05:19:49
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectlunar` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `projectlunar` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectlunar`.`user` (
  `uID` INT NOT NULL COMMENT 'Primary Key : User ID {incremental number to identify sum or as number identity for user}',
  `uName` VARCHAR(13) NULL COMMENT 'account username, a unique word. for login purpose',
  `pWord` VARCHAR(18) NULL COMMENT 'account password',
  `name` VARCHAR(18) NULL COMMENT 'real life name, for identification purpose.',
  `pID` INT NULL COMMENT 'product ID. a relation key to product table',
  `level` VARCHAR(8) NULL COMMENT 'user level. for privileges purpose',
  `isActive` BINARY NULL COMMENT 'Flag for checking activity of user (1 = active 0 =inactive)',
  PRIMARY KEY (`uID`),
  UNIQUE INDEX `uName_UNIQUE` (`uName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectlunar`.`product` (
  `pID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(13) NULL,
  `sID` INT NULL,
  PRIMARY KEY (`pID`),
  UNIQUE INDEX `uName_UNIQUE` (`name` ASC),
  UNIQUE INDEX `pID_UNIQUE` (`pID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectlunar`.`Transaction` (
  `tID` INT NOT NULL AUTO_INCREMENT COMMENT 'ID transaksi',
  `uID` INT NULL COMMENT 'relation key to user tab',
  `date` DATE NULL,
  `name` VARCHAR(18) NULL,
  `price` INT NULL,
  `phone` INT NULL,
  PRIMARY KEY (`tID`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectlunar`.`Price` (
  `prID` INT NOT NULL AUTO_INCREMENT,
  `price` INT NULL,
  PRIMARY KEY (`prID`),
  UNIQUE INDEX `uName_UNIQUE` (`price` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectlunar`.`Store` (
  `sID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(21) NULL,
  PRIMARY KEY (`sID`),
  UNIQUE INDEX `uName_UNIQUE` (`name` ASC),
  UNIQUE INDEX `sID_UNIQUE` (`sID` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
